### ISSUE TITLE
Error while running an application

### ISSUE THREAD

**Issue by Topiya** [vasani-arpit/cordova-plugin-downloadmanager#3]
Hello,
I am getting below error while running an application.

```
ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'download' of undefined
TypeError: Cannot read property 'download' of undefined
    at file:///android_asset/www/build/main.js:200:44
    at t.invoke (file:///android_asset/www/build/polyfills.js:3:14976)
    at Object.zone._inner.zone._inner.fork.onInvoke (file:///android_asset/www/build/vendor.js:4979:33)
    at t.invoke (file:///android_asset/www/build/polyfills.js:3:14916)
    at r.run (file:///android_asset/www/build/polyfills.js:3:10143)
    at file:///android_asset/www/build/polyfills.js:3:20242
    at t.invokeTask (file:///android_asset/www/build/polyfills.js:3:15660)
    at Object.zone._inner.zone._inner.fork.onInvokeTask (file:///android_asset/www/build/vendor.js:4970:33)
    at t.invokeTask (file:///android_asset/www/build/polyfills.js:3:15581)
    at r.runTask (file:///android_asset/www/build/polyfills.js:3:10834)
TypeError: Cannot read property 'download' of undefined
    at file:///android_asset/www/build/main.js:200:44
    at t.invoke (file:///android_asset/www/build/polyfills.js:3:14976)
    at Object.zone._inner.zone._inner.fork.onInvoke (file:///android_asset/www/build/vendor.js:4979:33)
    at t.invoke (file:///android_asset/www/build/polyfills.js:3:14916)
    at r.run (file:///android_asset/www/build/polyfills.js:3:10143)
    at file:///android_asset/www/build/polyfills.js:3:20242
    at t.invokeTask (file:///android_asset/www/build/polyfills.js:3:15660)
    at Object.zone._inner.zone._inner.fork.onInvokeTask (file:///android_asset/www/build/vendor.js:4970:33)
    at t.invokeTask (file:///android_asset/www/build/polyfills.js:3:15581)
    at r.runTask (file:///android_asset/www/build/polyfills.js:3:10834)
    at c (file:///android_asset/www/build/polyfills.js:3:19752)
    at file:///android_asset/www/build/polyfills.js:3:20273
    at t.invokeTask (file:///android_asset/www/build/polyfills.js:3:15660)
    at Object.zone._inner.zone._inner.fork.onInvokeTask (file:///android_asset/www/build/vendor.js:4970:33)
    at t.invokeTask (file:///android_asset/www/build/polyfills.js:3:15581)
    at r.runTask (file:///android_asset/www/build/polyfills.js:3:10834)
    at o (file:///android_asset/www/build/polyfills.js:3:7894)defaultErrorLogger @ vendor.js:1703
```

Can you provide any suggestion to solve this?

**Comment by vasani-arpit** [comment]
Which Framework you are using ?
This doesn't seem like Cordova callstack.

**Comment by Topiya** [comment]
I am using Ionic 3 framework

**Comment by vasani-arpit** [comment]
This plugin is tested in pure Cordova and ionic 1.
I haven't explored ionic 3.

basically whenever you want to call this plugin you must have access to Cordova.plugins object.

**Comment by Topiya** [comment]
Okay, Thank you
